[build]
target = "x86_64-hamix_os.json"

rustflags = [
    "-C", "link-arg=-Tsrc/../linker.ld",
    "-C", "link-arg=--build-id=none",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
