[workspace]
members = [
    "kernel",
    "sdk/hamix_std",
    "apps/hsh",
    "apps/hello_world",
    "apps/hxserver",
    "drivers/intel-graphics-driver",
    "libs/vellum",
    "libs/mini_png",
    "apps/hed",
]
resolver = "2"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
panic = "abort"
opt-level = 2
