[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cc = "1.0"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
spin = "0.9"
hxvt = { path = "../libs/hxvt" }
hext = { path = "../libs/hext" }
smoltcp = { path = "../libs/smoltcp", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "proto-dhcpv4", "proto-dns", "socket-udp", "socket-tcp", "socket-icmp", "socket-dhcpv4", "socket-dns"] }
