[package]
name = "hxvideo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hxvideo"
path = "src/main.rs"

[dependencies]
hamix_std = { path = "../../sdk/hamix_std" }
vellum = { path = "../../libs/vellum" }
hxclient = { path = "../../libs/hxclient" }
hx264 = { path = "../../libs/hx264" }
hxmp4 = { path = "../../libs/hxmp4" }
hxaac = { path = "../../libs/hxaac" }
